[supervisord]
nodaemon=true
logfile=/var/www/storage/logs/supervisord.log
pidfile=/var/run/supervisord.pid

[program:laravel-server]
command=php artisan serve --host=0.0.0.0 --port=8000
directory=/var/www
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/laravel-server.log
stderr_logfile=/var/www/storage/logs/laravel-server-error.log

[program:mqtt-listener]
command=php artisan mqtt:ecouter
directory=/var/www
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/mqtt-listener.log
stderr_logfile=/var/www/storage/logs/mqtt-listener-error.log